Repository andela/savage_rangers-ah-frontend, pull requests merged in 2019-08, with the labels that each got.

#8 #167619182 intergrate eslint rules
  .eslintignore
  .eslintrc.json
  .gitignore
  .hound.yml
  configs/axios.js
  package.json
  src/App/ApiActions/fetchHome.js
  src/App/ApiActions/index.js
  src/App/App.js
  src/App/Components/Home/Home.js
  src/App/Components/Login/Login.js
  src/App/Components/NotFound/NotFound.js
  src/App/Components/TestRedux.js
  src/App/_tests_/Actions.test.js
  src/App/_tests_/Home.test.js
  src/Redux/Actions/index.js
  src/Redux/Actions/testReduxActions.js
  src/Redux/Reducers/index.js
  src/Redux/Reducers/testReduxReducer.js
  src/Redux/store.js
  src/__mocks__/axios.js
  src/enzyme.js
  src/index.js
  webpack.config.js
Labels: Need Approval

#10 #[166240781] Users should be able to Login via Google Facebook or Twitter
  .eslintrc.json
  .hound.yml
  package.json
  src/App/App.js
  src/App/Components/Login/Login.js
  src/App/Components/Redirection/redirect.js
  src/App/Components/Separator/or_separator.js
  src/App/Components/SocialLogin/socialLogin.js
  src/App/_tests_/Redirect.test.js
  src/App/_tests_/Separator.test.js
  src/App/_tests_/SocialLogin.test.js
  src/Style/Sass/abstract/_variables.scss
  src/Style/Sass/component/_buttons.scss
  src/Style/Sass/component/_separator.scss
  src/Style/Sass/main.scss
  src/Style/Sass/pages/_redirection.scss
  webpack.config.js
Labels: Need Review

#9 166240777 allow user to register
  .eslintrc.json
  configs/axios.js
  package.json
  src/App/App.js
  src/App/Components/Common/Alert.js
  src/App/Components/Common/Footer.js
  src/App/Components/Common/NavProfile/navLogo.js
  src/App/Components/Common/NavProfile/navbar.js
  src/App/Components/Redirection/redirect.js
  src/App/Components/Registration/Registration.js
  src/App/Components/SocialLogin/socialLogin.js
  src/App/_tests_/Actions.test.js
  src/App/_tests_/Alert.test.js
  src/App/_tests_/Footer.test.js
  src/App/_tests_/NavLogo.test.js
  src/App/_tests_/Navbar.test.js
  src/App/_tests_/Registration.test.js
  src/App/_tests_/SocialLogin.test.js
  src/Redux/Actions/Registration.js
  src/Redux/Actions/index.js
  src/Redux/Reducers/Registration.js
  src/Redux/Reducers/index.js
  src/Style/Sass/abstract/_common.scss
  src/Style/Sass/abstract/_variables.scss
  src/Style/Sass/base/_base.scss
  src/Style/Sass/component/_buttons.scss
  src/Style/Sass/component/_navLink.scss
  src/Style/Sass/component/_navLogo.scss
  src/Style/Sass/component/_navProfile.scss
  src/Style/Sass/component/_separator.scss
  src/Style/Sass/layout/_footer.scss
  src/Style/Sass/layout/_navigation.scss
  src/Style/Sass/main.scss
  src/Style/Sass/pages/_redirection.scss
  src/Style/Sass/pages/_registration.scss
  src/__mocks__/axios.js
Labels: under review

#13 #166240780 implement login frontend
  .eslintrc.json
  configs/request.js
  package.json
  src/App/App.js
  src/App/Components/Common/Alert.js
  src/App/Components/Inputs/index.js
  src/App/Components/Login/Login.js
  src/App/Components/Login/index.js
  src/App/_tests_/Actions.test.js
  src/App/_tests_/Actions/auth.test.js
  src/App/_tests_/Components/Inputs.test.js
  src/App/_tests_/Components/__snapshots__/Inputs.test.js.snap
  src/App/_tests_/ForgotPassword.test.js
  src/App/_tests_/Login.test.js
  src/App/_tests_/Reducers.test.js
  src/App/_tests_/Redux/Reducers/alert .test.js
  src/App/_tests_/ResetPassword.test.js
  src/App/_tests_/__snapshots__/Login.test.js.snap
  src/Redux/Actions/auth.js
  src/Redux/Actions/types.js
  src/Redux/Reducers/auth.js
  src/Redux/Reducers/index.js
  src/Redux/store.js
  src/Style/Sass/abstract/_mixin.scss
  src/Style/Sass/abstract/common.scss
  src/Style/Sass/component/_buttons.scss
  src/Style/Sass/component/_separator.scss
  src/Style/Sass/main.scss
  src/Style/Sass/pages/_auth.scss
  src/configs/axios.js
  src/index.js
Labels: Need Review

#19 #167938539 terms conditions frontend
  src/App/App.js
  src/App/Components/Registration/Registration.js
  src/App/Components/TermsAndConditions/index.js
  src/App/_tests_/Actions/termsactions.test.js
  src/App/_tests_/Redux/Reducers/termsreducer.test.js
  src/App/_tests_/terms.test.js
  src/Redux/Actions/index.js
  src/Redux/Actions/terms.js
  src/Redux/Reducers/index.js
  src/Redux/Reducers/termsAndcondReducers.js
  src/Style/Sass/component/_navLogo.scss
  src/Style/Sass/component/_navProfile.scss
  src/Style/Sass/layout/_termsAndConditions.scss
  src/Style/Sass/main.scss
Labels: Need Review
