Repository andela/savage_rangers-ah-frontend, pull requests merged in 2019-09, with the labels that each got.

#14 #166240784 User should be able to read/display an article.
  .babelrc
  .eslintrc.json
  package.json
  src/App/App.js
  src/App/Components/ArticleNotFound/ArticleNotFound.js
  src/App/Components/Common/loader.js
  src/App/Components/DisplayArticle/articleBody.js
  src/App/Components/DisplayArticle/breadCrumb.js
  src/App/Components/DisplayArticle/readArticle.js
  src/App/Components/DisplayArticle/tags.js
  src/App/Components/NotFound/NotFound.js
  src/App/Components/Popular/bottom-popular.js
  src/App/Components/Popular/popular.js
  src/App/Components/SocialButtons/Social.button.js
  src/App/_tests_/ArticleNotFound.test.js
  src/App/_tests_/Bottom.popular.test.js
  src/App/_tests_/NotFound.test.js
  src/App/_tests_/__snapshots__/ArticleNotFound.test.js.snap
  src/App/_tests_/__snapshots__/Bottom.popular.test.js.snap
  src/App/_tests_/__snapshots__/article.body.test.js.snap
  src/App/_tests_/__snapshots__/breadCrumb.test.js.snap
  src/App/_tests_/__snapshots__/popular.test.js.snap
  src/App/_tests_/__snapshots__/readArticle.test.js.snap
  src/App/_tests_/__snapshots__/tags.test.js.snap
  src/App/_tests_/article.body.test.js
  src/App/_tests_/breadCrumb.test.js
  src/App/_tests_/popular.test.js
  src/App/_tests_/readArticle.test.js
  src/App/_tests_/tags.test.js
  src/Redux/Actions/index.js
  src/Redux/Actions/readArticleActions.js
  src/Redux/Actions/readPopularActions.js
  src/Redux/Reducers/index.js
  src/Redux/Reducers/popularArticleReducer.js
  src/Redux/Reducers/readArticleReducer.js
  src/Style/Assets/b2.jpg
  src/Style/Sass/abstract/_mixin.scss
  src/Style/Sass/abstract/_variables.scss
  src/Style/Sass/component/_bottom-popular.scss
  src/Style/Sass/component/_displayArticle.scss
  src/Style/Sass/component/_loader.scss
  src/Style/Sass/layout/_editor.scss
  src/Style/Sass/layout/_navbar.scss
  src/Style/Sass/main.scss
  src/Style/Sass/pages/_articleNotFound.scss
  webpack.config.js
Labels: Need Review

#24 ft-166240798 allow user to bookmark an article
  src/App/Components/Common/Bookmark/Bookmark.js
  src/App/Components/DisplayArticle/readArticle.js
  src/App/_tests_/Bookmark.test.js
  src/App/_tests_/readArticle.test.js
  src/Helpers/compareBookmarks.js
  src/Redux/Actions/auth.js
  src/Redux/Actions/bookmark.js
  src/Redux/Actions/index.js
  src/Redux/Actions/notifications.js
  src/Redux/Reducers/Bookmark.js
  src/Redux/Reducers/index.js
  src/Style/Sass/component/_bookmark.scss
  src/Style/Sass/main.scss
Labels: Need Review

#27 #166240791 share article via social media
  public/index.html
  src/App/Components/ArticleSocialSharing/ArticleSocialSharing.js
  src/App/Components/DisplayArticle/readArticle.js
  src/App/_tests_/socialSharing.test.js
  src/Style/Sass/component/_bookmark.scss
  src/Style/Sass/layout/_socialSharing.scss
  src/Style/Sass/main.scss
Labels: Need Review

#23 #168049548 Fetch all authors
  src/App/App.js
  src/App/Components/authors/authorcomponent/index.js
  src/App/Components/authors/index.js
  src/App/_tests_/Actions/authors.test.js
  src/App/_tests_/Actions/follow.test.js
  src/App/_tests_/Redux/Reducers/authors.test.js
  src/App/_tests_/authors.test.js
  src/Redux/Actions/Follow.js
  src/Redux/Actions/authors.js
  src/Redux/Actions/index.js
  src/Redux/Reducers/authors.js
  src/Redux/Reducers/index.js
  src/Style/Sass/layout/_authorPagination.scss
  src/Style/Sass/layout/_authors.scss
  src/Style/Sass/main.scss
  src/assets/assets/myAvatar.png
Labels: Need Merge

#16 #167816359 allow user to access all articles
  .eslintrc.json
  package.json
  src/App/App.js
  src/App/Components/Articles/getArticles/Article.js
  src/App/Components/Articles/getArticles/Articles.js
  src/App/_tests_/articles/__snapshots__/article.test.js.snap
  src/App/_tests_/articles/__snapshots__/articles.test.js.snap
  src/App/_tests_/articles/article.test.js
  src/App/_tests_/articles/articles.actions.test.js
  src/App/_tests_/articles/articles.js
  src/App/_tests_/articles/articles.test.js
  src/App/_tests_/articles/search.test.js
  src/Helpers/countRating.js
  src/Redux/Actions/GET_ARTICLES.js
  src/Redux/Actions/getArticles.js
  src/Redux/Actions/index.js
  src/Redux/Actions/searchArticle.js
  src/Redux/Reducers/articles.js
  src/Redux/Reducers/index.js
  src/Redux/Reducers/searchArticle.js
  src/Style/Sass/abstract/_variables.scss
  src/Style/Sass/component/_articles.scss
  src/Style/Sass/component/_articles_error.scss
  src/Style/Sass/component/_label.scss
  src/Style/Sass/layout/_footer.scss
  src/Style/Sass/main.scss
  src/Style/Sass/pages/_articleNotFound.scss
  webpack.config.js
Labels: Need Review

#33 #166240803 Users should be able to like a specific comment
  .eslintrc.json
  src/App/Components/Comment/comment.holder.js
  src/App/Components/Comment/comment.icons.js
  src/App/Components/Comment/parent.comment.body.js
  src/App/Components/Comment/reply.comment.body.js
  src/App/Components/Common/LoginFirstToast.js
  src/App/Components/DisplayArticle/readArticle.js
  src/App/Components/Login/index.js
  src/App/_tests_/__snapshots__/comment.holder.test.js.snap
  src/App/_tests_/articles/__snapshots__/articles.test.js.snap
  src/App/_tests_/comment.holder.test.js
  src/App/_tests_/comment.icons.test.js
  src/App/_tests_/reply.comment.test.js
  src/Redux/Actions/getAllComments.js
  src/Redux/Actions/index.js
  src/Redux/Reducers/comments.js
  src/Style/Sass/component/_comment.body.scss
  src/Style/Sass/layout/_loginFirst.scss
  src/Style/Sass/main.scss
Labels: Need Merge

#30 #166240785 Allow users to rate articles
  package.json
  src/App/App.js
  src/App/Components/Common/NavProfile/Profile.js
  src/App/Components/Common/TriangularPopup.js
  src/App/Components/DisplayArticle/Rating.js
  src/App/Components/DisplayArticle/Ratings.js
  src/App/Components/DisplayArticle/readArticle.js
  src/App/_tests_/AvarageCalculator.test.js
  src/App/_tests_/rating.test.js
  src/App/_tests_/ratings.test.js
  src/Helpers/calculateAverageRating.js
  src/Redux/Actions/articleRatings.js
  src/Redux/Actions/index.js
  src/Redux/Reducers/articleRatings.js
  src/Redux/Reducers/index.js
  src/Style/Sass/component/_rater.scss
  src/Style/Sass/layout/_notifications.scss
  src/Style/Sass/layout/_ratings.scss
  src/Style/Sass/main.scss
Labels: depends-on-readArticle

#36 #166240801 highlight and comment article
  package.json
  src/App/Components/DisplayArticle/HighlightArticle.js
  src/App/Components/DisplayArticle/articleBody.js
  src/App/Components/DisplayArticle/readArticle.js
  src/App/Components/DisplayArticle/sampletest1
  src/App/Components/DisplayArticle/testing-2
  src/App/_tests_/Actions/highlight.test.js
  src/App/_tests_/Redux/Reducers/highlight.test.js
  src/App/_tests_/highlight.test.js
  src/App/_tests_/readArticle.test.js
  src/Redux/Actions/getHighlight.js
  src/Redux/Actions/index.js
  src/Redux/Actions/postHighlight.js
  src/Redux/Reducers/Registration.js
  src/Redux/Reducers/highlight.js
  src/Redux/Reducers/index.js
  src/__mocks__/window.js
  src/configs/axios.js
Labels: WIP
